# Analisis Data Anime

Tujuan : Menganalisis rating anime dari dataset CSV.

## 1.Tampilkan Data

In [1]:
import pandas as pd

df = pd.read_csv("anime.csv")

df

                                   judul  rating  release
0       Fullmetal Alchemist: Brotherhood    9.10     2009
1                            Steins;Gate    9.07     2011
2                                   Pupa    3.31     2014
3                       Sword Art Online    7.20     2012
4                            School Days    5.54     2007
5                    Mars of Destruction    2.22     2005
6                          Spirited Away    8.78     2001
7                                 Ex-Arm    2.31     2021
8                        Attack on Titan    9.05     2013
9        Boruto: Naruto Next Generations    5.82     2017
10                        Skelter+Heaven    1.84     2004
11                      My Hero Academia    7.85     2016
12                    Domestic na Kanojo    6.68     2019
13                               Gibiate    3.84     2020
14                             One Piece    8.72     1999
15                          Hand Shakers    5.31     2017
16                               Redline    8.21     2009
17                     Rent-a-Girlfriend    7.02     2020
18                          Demon Slayer    8.60     2019
19                    Ghost in the Shell    8.25     1995
20                          Cowboy Bebop    8.75     1998
21                               Gintama    8.94     2006
22                       Hunter x Hunter    9.04     2011
23                             Your Name    8.85     2016
24                          Vinland Saga    8.74     2019
25                               Monster    8.87     2004
26                     Mob Psycho 100 II    8.80     2019
27                     Violet Evergarden    8.67     2018
28                  Clannad: After Story    8.94     2008
29                              Mushishi    8.66     2005
30                            Fairy Tail    7.57     2009
31                    Tokyo Ghoul Root A    7.03     2015
32  Seven Deadly Sins: Wrath of the Gods    6.43     2019
33                 Darling in the Franxx    7.20     2018
34                         Blue Exorcist    7.51     2011
35                          Platinum End    6.77     2021
36                    Record of Ragnarok    6.67     2021
37                       High School DxD    7.35     2012
38                          Black Clover    8.15     2017
39                             Dr. Stone    8.28     2019
40                               Ladyspo    2.34     2018
41                            Conception    4.53     2018
42                     Forest Fairy Five    3.31     2017
43                                Hanoka    3.56     2006
44                        Vampire Holmes    3.34     2015
45                        Abunai Sisters    2.44     2009
46                         Dynamic Chord    3.41     2017
47                 Twinkle Nora Rock Me!    2.12     1985
48                          Psychic Wars    3.15     1991
49                   Generation of Chaos    3.48     2001

## 2. Analisis Data

### 2.1 Filter

#### 2.1.1 Filter Rating
Tujuan : Filter anime berdasarkan rating.

In [6]:
# RATING 0-3
df[df["rating"] < 4]

                    judul  rating  release
2                    Pupa    3.31     2014
5     Mars of Destruction    2.22     2005
7                  Ex-Arm    2.31     2021
10         Skelter+Heaven    1.84     2004
13                Gibiate    3.84     2020
40                Ladyspo    2.34     2018
42      Forest Fairy Five    3.31     2017
43                 Hanoka    3.56     2006
44         Vampire Holmes    3.34     2015
45         Abunai Sisters    2.44     2009
46          Dynamic Chord    3.41     2017
47  Twinkle Nora Rock Me!    2.12     1985
48           Psychic Wars    3.15     1991
49    Generation of Chaos    3.48     2001

In [8]:
# RATING 4-7
df[(df["rating"] >= 4) & (df["rating"] <= 7)]

                                   judul  rating  release
4                            School Days    5.54     2007
9        Boruto: Naruto Next Generations    5.82     2017
12                    Domestic na Kanojo    6.68     2019
15                          Hand Shakers    5.31     2017
32  Seven Deadly Sins: Wrath of the Gods    6.43     2019
35                          Platinum End    6.77     2021
36                    Record of Ragnarok    6.67     2021
41                            Conception    4.53     2018

In [9]:
# RATING 8-10
df[df["rating"] > 7]

                               judul  rating  release
0   Fullmetal Alchemist: Brotherhood    9.10     2009
1                        Steins;Gate    9.07     2011
3                   Sword Art Online    7.20     2012
6                      Spirited Away    8.78     2001
8                    Attack on Titan    9.05     2013
11                  My Hero Academia    7.85     2016
14                         One Piece    8.72     1999
16                           Redline    8.21     2009
17                 Rent-a-Girlfriend    7.02     2020
18                      Demon Slayer    8.60     2019
19                Ghost in the Shell    8.25     1995
20                      Cowboy Bebop    8.75     1998
21                           Gintama    8.94     2006
22                   Hunter x Hunter    9.04     2011
23                         Your Name    8.85     2016
24                      Vinland Saga    8.74     2019
25                           Monster    8.87     2004
26                 Mob Psycho 100 II    8.80     2019
27                 Violet Evergarden    8.67     2018
28              Clannad: After Story    8.94     2008
29                          Mushishi    8.66     2005
30                        Fairy Tail    7.57     2009
31                Tokyo Ghoul Root A    7.03     2015
33             Darling in the Franxx    7.20     2018
34                     Blue Exorcist    7.51     2011
37                   High School DxD    7.35     2012
38                      Black Clover    8.15     2017
39                         Dr. Stone    8.28     2019

#### 2.1.2 Filter Tahun Rilis
Tujuan : Filter anime berdasarkan tahun rilis.

In [ ]:
# SEBELUM TAHUN 2000
df[df["release"] < 2000]

                    judul  rating  release
14              One Piece    8.72     1999
19     Ghost in the Shell    8.25     1995
20           Cowboy Bebop    8.75     1998
47  Twinkle Nora Rock Me!    2.12     1985
48           Psychic Wars    3.15     1991

In [12]:
# SETELAH TAHUN 2000
df[df["release"] >= 2000]

                                   judul  rating  release
0       Fullmetal Alchemist: Brotherhood    9.10     2009
1                            Steins;Gate    9.07     2011
2                                   Pupa    3.31     2014
3                       Sword Art Online    7.20     2012
4                            School Days    5.54     2007
5                    Mars of Destruction    2.22     2005
6                          Spirited Away    8.78     2001
7                                 Ex-Arm    2.31     2021
8                        Attack on Titan    9.05     2013
9        Boruto: Naruto Next Generations    5.82     2017
10                        Skelter+Heaven    1.84     2004
11                      My Hero Academia    7.85     2016
12                    Domestic na Kanojo    6.68     2019
13                               Gibiate    3.84     2020
15                          Hand Shakers    5.31     2017
16                               Redline    8.21     2009
17                     Rent-a-Girlfriend    7.02     2020
18                          Demon Slayer    8.60     2019
21                               Gintama    8.94     2006
22                       Hunter x Hunter    9.04     2011
23                             Your Name    8.85     2016
24                          Vinland Saga    8.74     2019
25                               Monster    8.87     2004
26                     Mob Psycho 100 II    8.80     2019
27                     Violet Evergarden    8.67     2018
28                  Clannad: After Story    8.94     2008
29                              Mushishi    8.66     2005
30                            Fairy Tail    7.57     2009
31                    Tokyo Ghoul Root A    7.03     2015
32  Seven Deadly Sins: Wrath of the Gods    6.43     2019
33                 Darling in the Franxx    7.20     2018
34                         Blue Exorcist    7.51     2011
35                          Platinum End    6.77     2021
36                    Record of Ragnarok    6.67     2021
37                       High School DxD    7.35     2012
38                          Black Clover    8.15     2017
39                             Dr. Stone    8.28     2019
40                               Ladyspo    2.34     2018
41                            Conception    4.53     2018
42                     Forest Fairy Five    3.31     2017
43                                Hanoka    3.56     2006
44                        Vampire Holmes    3.34     2015
45                        Abunai Sisters    2.44     2009
46                         Dynamic Chord    3.41     2017
49                   Generation of Chaos    3.48     2001

### 2.2 Statistik
Tujuan : Mengkalkulasi statistik dari data anime.

#### 2.2.1 Mean

In [ ]:
df["rating"].mean()